import React from "react";
import PageTitle from "../../components/PageTitle";

const Terms = () => {
	return (
		<div className="container" style={{ paddingTop: "120px" }}>
			<PageTitle title="Term & Conditions | LikeFit" description="term likefit" />
			<nav aria-label="breadcrumb">
				<ol className="breadcrumb">
					<li className="breadcrumb-item">
						<a href="../index.html" className="pr-3">
							LikeFit
						</a>
					</li>
					<li className="breadcrumb-item">
						<a href="../components.html">Term & Conditions</a>
					</li>
				</ol>
			</nav>
			<div className="policy py-4">
				<div className="card">
					<div className="card-body" style={{ width: "90%", margin: "0 auto", textAlign: "justify" }}>
						<h3 className="text-center">Term & Conditions</h3>
						<p className="card-text py-2 font-16">
							LikeFit's advisory policy is to help you understand what data LikeFit collects about you,
							why it collects it, and what LikeFit does with that data. You have trusted in using LikeFit
							and sharing information with LikeFit, so LikeFit is committed to only using your information
							to create better services for you.
						</p>
						<h6 className="py-2">1. Grant of License</h6>
						<p className="card-text py-2">
							Subject to the terms of these TOS, you are granted a limited, non-exclusive,
							non-transferable, and revocable licence to install, access, and use the SERVICE for your
							personal and non-commercial use.
						</p>
						<p className="card-text py-2">
							The services and features provided by the SERVICE or Update (defined below) thereto may vary
							or be limited depending on certain factors, including, without limitation, your country,
							device, operating system, or service provider.
						</p>
						<p className="card-text py-2">
							If you are under the age of 14, you may not use the SERVICE. If you are 14 or older but
							under the majority age in your jurisdiction, you must review these TOS with your parent or
							legal guardian to be sure you and your parent or guardian understand and consent to these
							TOS. Your parent or guardian must accept these TOS. If you are a parent or guardian
							permitting a person under the age of majority in your jurisdiction (“Minor”) to use the
							SERVICE, you agree to: (i) supervise the Minor’s use of the SERVICE; (ii) assume all risks
							associated with the Minor’s use of the SERVICE; (iii) assume any liability resulting from
							the Minor’s use of the SERVICE; (iv) ensure the accuracy and truthfulness of all information
							submitted by the Minor; and (v) assume responsibility and are bound by these TOS for the
							Minor’s access and use of the SERVICE.
						</p>
						<h6 className="py-2">2. Reservation of Rights and Ownership</h6>
						<p className="card-text py-2">
							All rights not expressly granted to you hereunder shall belong to LIKE FIT. This SERVICE
							includes software and data provided by third parties. You acknowledge that all articles,
							text, software, music, sound, photographs, graphics, video, page layouts, design and other
							material available on or through the SERVICE and its applications and all intellectual
							property rights therein (collectively, the “LIKE FIT Contents and IPR”) are proprietary to
							LIKE FIT and its third-party licensors, and protected under applicable copyright and other
							intellectual property laws and treaties. These TOS and your use of the SERVICE do not grant
							you any ownership interest in or to the SERVICE or the LIKE FIT Contents and IPR, or any
							data generated by other users of the SERVICE, and you are granted only a limited licence to
							use that is revocable in accordance with the terms of these TOS. You may not use the SERVICE
							to reproduce copyrighted materials, or materials to which you do not have the right or legal
							approval for reproduction.
						</p>
						<h6 className="py-2">3. Restrictions</h6>
						<p className="card-text py-2">
							You may not (i) reverse engineer, decompile, disassemble, or otherwise attempt to discover
							the source code or algorithms of the SERVICE except as permitted by applicable law in the
							jurisdiction where you are a resident; (ii) modify or disable any features of the SERVICE;
							(iii) create derivative works based on the SERVICE, except to the extent that your local law
							requires you to be able to do so; (iv) rent, lease, lend, sublicense, or provide commercial
							hosting services with the SERVICE; (v) infringe LIKE FIT’s intellectual property rights or
							those of any third party in relation to your use of the SERVICE (to the extent that such use
							is not licensed by these TOS); (vi) use the SERVICE in any unlawful manner, for any unlawful
							purpose, or in any commercial manner, for any commercial purpose, or in any manner
							inconsistent with these TOS, or act fraudulently or maliciously, for example, by hacking
							into or inserting malicious code, including viruses, or harmful data, into the SERVICE or
							any operating system; (vii) use the SERVICE in a way that could damage, disable, overburden,
							impair or compromise our systems or security or interfere with other users; and (viii)
							collect or harvest any information or data from the SERVICE or our systems or attempt to
							decipher any transmissions to or from the servers running the SERVICE; and/or (ix) do any
							other act or omit to do any other act which may harm or otherwise prejudice any of the
							SERVICE and/or the LIKE FIT Contents and IPR.
						</p>
						<p className="card-text py-2">Representations</p>
						<p className="card-text py-2">
							By submitting or posting any audio, visual, images, comments, profiles, or other written or
							graphic materials (“Content”) to the SERVICE, you make the legally binding representations
							set forth below about yourself, how the Content was created, what it contains and certain
							other information, and you understand and intend that LIKE FIT rely on these
							representations:
							<br />
							<p className="card-text py-2">
								If you are the creator of the Content, the Content is your original work and you own it.
								If created by or with others, you have, or else you have obtained the consent,
								authorisation, and all of the legal rights from all of the creators or persons or
								entities who have rights in the Content which are necessary for you to submit it to LIKE
								FIT and for LIKE FIT to distribute and exercise the other rights in this TOS respecting
								the Content.
							</p>
							<p className="card-text py-2">
								You hereby grant LIKE FIT the right to use, copy, modify, reproduce, or distribute any
								and all of your Content. You also acknowledge and agree that LIKE FIT may modify,
								delete, or hide your Content without notice.
							</p>
							<p className="card-text py-2">
								Listing, marketing, delivery, installation, uploading, and use of your Content on the
								SERVICE does not violate any agreements to which you are a party or of which you are
								otherwise aware. If your Content includes any open source software, your Content
								complies with any corresponding licence obligations for such open source software, and
								will not cause any software or technology used or comprising the SERVICE to be disclosed
								or otherwise become part of the public domain.
							</p>
						</p>
						<p className="card-text py-2">
							The Content is not:
							<br /> o libellous or defamatory; o obscene, pornographic, sexually explicit, or vulgar, and
							does not depict nudity or any sexual acts; o predatory, hateful, or intended to intimidate
							or harass any person, and does not contain derogatory name-calling; o in poor taste or is
							otherwise objectionable, and
						</p>
						<p className="card-text py-2">
							The Content does not: <br />o infringe upon or violate the copyrights, trademarks, or other
							intellectual property rights of any person or entity.
							<br />o violate any person’s right to privacy, publicity, or personality;
							<br />o violate any local, state, federal, national, or international law, including any US
							or foreign export control laws, or the applicable laws of each jurisdiction to which You are
							submitting the Content for distribution
							<br />o contain any viruses, hidden matter, or other malicious elements (including, for
							example, any “trap doors”, “worms”, “Trojans”, or “time bombs”) or other unauthorised or
							hidden programmes
							<br />o collect any user information for which You have not obtained the user’s consent;
							<br />o contain or advocate illegal or violent acts;
							<br />o degrade any person on the basis of gender, race, class, ethnicity, national origin,
							religion, sexual orientation, disability, or other classification;
							<br />o contain any prohibited content (as identified in the Documentation, which is defined
							below
							<br />o contain advertising;
							<br />o contain a solicitation of any kind;
							<br />o misrepresent Your identity or affiliation;
							<br />o impersonate others.
						</p>
						<p className="card-text py-2">
							If these representations are false in any way, you will be responsible for any damages or
							losses that LIKE FIT suffers as a result. In addition, if you discover that any Content
							violates these representations or that it is otherwise inappropriate, or LIKE FIT requests
							that you do so, you will immediately remove any Content that you have posted from the
							SERVICE.
						</p>
						<h6 className="py-2">4. Update, Change or Suspension of the SERVICE</h6>
						<p className="card-text py-2">
							LIKE FIT may, at any time, provide or make available updates or upgrades to the SERVICE
							(“Updates”), including without limitation, changing the name of the SERVICE, bug fixes,
							service enhancements, new features, deletion of existing functions, or modification of the
							SERVICE. Updates will be governed by these TOS unless separate terms and conditions are
							provided with such Updates which will be duly and timely notified to you, in which case
							those separate terms and conditions shall govern the Updates. Updates for security software,
							critical bug fixes, or other important Updates may be downloaded and installed once you have
							been notified of the importance of receiving such Updates in a timely manner.
						</p>
						<p className="card-text py-2">
							LIKE FIT shall nevertheless be under no obligation to provide any Updates or modifications
							to the SERVICE.
						</p>
						<p className="card-text py-2">
							LIKE FIT expressly reserves the right to change, suspend, remove, limit the use of, or
							disable the access to the SERVICE or any portion thereof at any time without notice or
							liability. It is essential that you back up your data on your device before using the
							services to avoid losing any data.
						</p>
						<h6 className="py-2">5. Third party Services and Content</h6>
						<p className="card-text py-2">
							Third-party services and/or content may also be available to you through the SERVICE. To the
							extent permitted by law, LIKE FIT disclaims any warranty, condition or representation in
							respect of any third-party services or content in any aspects including, but not limited to,
							quality, accuracy, effectiveness, lack of viruses, non-infringement of third-party rights,
							and compliance with any applicable laws or regulations. The use of third-party services and
							content may be governed by the terms of use, any licence agreements, privacy policies, or
							other such agreements of the third-party providers. Certain portions of the SERVICE may be
							subject to open source licences, in which case the terms of such open source licences may
							precede the terms of these TOS with respect to that portion of the SERVICE.
						</p>
						<h6 className="py-2">6. Consent for Collection and Use of Data</h6>
						<p className="card-text py-2">
							You acknowledge and agree that LIKE FIT and/or parties that are entrusted by LIKE FIT may
							collect and use information including your sensitive personal data, necessary to provide the
							SERVICE and Updates, and improve or enhance the SERVICE. At all times your information will
							be treated in accordance with the applicable laws and LIKE FIT’s Privacy Policy, which can
							be viewed at: https://account.LIKE FIT.com/membership/pp. Also, you can find the LIKE FIT
							Privacy Notice to learn more about the information collected through LIKE FIT at:
							https://LIKE FIThealth.com/privacy. LIKE FIT may update the Privacy Policy or the LIKE FIT
							Health Privacy Notice from time to time, so please periodically review the Privacy Policy
							and the LIKE FIT Privacy Notice.
						</p>
						<h6 className="py-2">7. Data Access</h6>
						<p className="card-text">
							Some features of the SERVICE may require your mobile device to have access to the internet
							and may be subject to restrictions imposed by your network or internet provider. The SERVICE
							may require access through your mobile network, which may result in additional charges
							depending on your payment plan. In addition, your enjoyment of some features of the SERVICE
							may be affected by the suitability and performance of your device hardware or data access.
						</p>
						<h6 className="py-2">8. Compliance with Law</h6>
						<p className="card-text">
							You acknowledge and agree to comply with any and all applicable laws and regulations in
							using the SERVICE including without limitation, all applicable export restriction laws and
							regulations.
						</p>
						<h6 className="py-2">9. Termination</h6>
						<p className="card-text">
							These TOS are effective upon your acceptance of these TOS, or upon your downloading,
							accessing or otherwise using the SERVICE. The SERVICE has no predetermined termination date
							and may continue until such time as either LIKE FIT or you terminate these TOS by notice to
							the respective other party or if it is otherwise terminated consistent with these TOS. You
							can terminate these TOS by ceasing your use of the SERVICE, and uninstalling, deleting and
							returning all related software, documentations, and other materials provided by LIKE FIT,
							including backup copies thereof. Should you not comply with these TOS, your rights based on
							these TOS will be automatically terminated. Upon termination of these TOS, you must
							immediately cease all use of the SERVICE. For the purposes of clarity, LIKE FIT may
							terminate these TOS and the SERVICE with notice to you (e.g. service website, pop-up through
							application, email, etc.).
						</p>
						<h6 className="py-2">10. Disclaimer of Warranty</h6>
						<p className="card-text">
							SUBJECT TO CLAUSE 11, LIKE FIT AND LIKE FIT CONTENTS AND IPR ARE PROVIDED “AS IS” AND ON AN
							“AS AVAILABLE” BASIS, WITHOUT WARRANTIES OR CONTRACTUAL CONDITIONS OF ANY KIND FROM LIKE FIT
							OR ITS THIRD-PARTY LICENSORS OR SUPPLIERS, EITHER EXPRESS OR IMPLIED. TO THE EXTENT
							PERMITTED BY LAW, LIKE FIT DISCLAIMS ALL WARRANTIES EXPRESSED, IMPLIED, OR STATUTORY,
							INCLUDING, BUT NOT LIMITED TO, IMPLIED WARRANTIES OF MERCHANTABILITY, SATISFACTORY QUALITY,
							FITNESS FOR A PARTICULAR PURPOSE, RELIABILITY, AVAILABILITY, ACCURACY, LACK OF VIRUSES,
							QUIET ENJOYMENT, NON INFRINGEMENT OF THIRD-PARTY RIGHTS, OR OTHER VIOLATION OF RIGHTS. NO
							ADVICE OR INFORMATION, WHETHER ORAL OR WRITTEN, OBTAINED BY YOU FROM LIKE FIT SHALL BE
							DEEMED TO ALTER THIS DISCLAIMER, OR TO CREATE ANY WARRANTY OF ANY SORT FROM LIKE FIT.
							WITHOUT LIMITING THE FOREGOING, LIKE FIT DOES NOT WARRANT THAT ACCESS TO LIKE FIT, OR ANY
							FEATURE OR FUNCTION THEREIN, WILL BE UNINTERRUPTED OR ERROR-FREE, OR THAT DEFECTS, IF ANY,
							WILL BE CORRECTED; NOR DOES LIKE FIT MAKE ANY REPRESENTATIONS ABOUT THE ACCURACY, SAFETY,
							RELIABILITY, CURRENCY, QUALITY, COMPLETENESS, USEFULNESS, PERFORMANCE, SECURITY, LEGALITY,
							OR SUITABILITY OF LIKE FIT OR ANY OF THE INFORMATION CONTAINED THEREIN.
						</p>
						<h6 className="py-2">11. Limitation of Liability</h6>
						<p className="card-text">
							TO THE EXTENT PERMITTED BY LAW, IN NO EVENT SHALL LIKE FIT OR ITS LICENSORS BE LIABLE TO YOU
							OR ANY PARTY YOU ALLOW TO USE THE SERVICE FOR ANY INDIRECT, INCIDENTAL, CONSEQUENTIAL,
							SPECIAL, EXEMPLARY, OR PUNITIVE DAMAGES, OR LOST PROFITS, EVEN IF EACH HAS BEEN ADVISED OF
							THE POSSIBILITY OF SUCH DAMAGES. THESE LIMITATIONS MAY NOT APPLY TO YOU IF A LAW OF A
							CERTAIN JURISDICTION DOES NOT ALLOW SUCH LIMITATIONS. YOU ACKNOWLEDGE AND AGREE THAT THE
							LIMITATIONS HEREIN ARE REASONABLE GIVEN THE BENEFITS OF THE SERVICES AND YOU WILL ACCEPT
							SUCH RISK AND/OR INSURE ACCORDINGLY.
						</p>
						<h6 className="py-2">12. Applicable Law</h6>
						<p className="card-text">
							These TOS are governed by the laws of the jurisdiction where you are a resident, without
							regard to its conflict of law provisions. These TOS shall not be governed by the UN
							Convention on Contracts for the International Sale of Goods, the application of which is
							expressly excluded. These TOS shall be subject to the non-exclusive jurisdiction of the
							courts of the Member State in which you are domiciled. To the extent permitted by law, You
							may also seek protection before a local tribunal.
						</p>
						<h6 className="py-2">13. Entire Agreement</h6>
						<p className="card-text">
							These TOS are the entire agreement between you and LIKE FIT relating to the SERVICE and
							supersede all prior or contemporaneous oral or written communications, proposals, and
							representations with respect to the SERVICE or any other subject matter covered by these
							TOS. If any provision of these TOS is held to be void, invalid, unenforceable, or illegal,
							the other provisions shall continue in full force and effect.
						</p>
						<p className="py-5">Last Updated on 17/10/2018</p>

						<a className="py-5 font-18" href="#" download>
							Term & Service download&nbsp; <i className="fas fa-download"></i>
						</a>
					</div>
				</div>
			</div>
		</div>
	);
};

export default Terms;
